package fr.modeetratheure;

import java.util.List;

public class Group {

    protected List<Player> players;
    protected List<Match> matchs;

    public Group(List<Player> players){
        this.players = players;
    }

    /**
     * Generate a list of two-player matches, where every player meets every other player.
     */
    public void generateMatchs(){
        for(int i = 0; i < players.size() - 1; i++){
            for(int j = i + 1; j < players.size() - i - 1; j++){
                matchs.add(new Match(List.of(players.get(i), players.get(j))));
            }
        }
    }


    /**
     * @return a list of the matches generated by {@link #generateMatchs()}.
     */
    public List<Match> getMatchs(){
        return matchs;
    }

    public List<Player> getPlayers(){
        return players;
    }

}
